#include <iostream>
using namespace std;
int main(){
	
setlocale(LC_ALL, "Russian");
	
    cout <<"\n\n\t\tцвета: 0-черный, 1-синий, 2-зеленый, 3-голубой,  4-красный,  5-лиловый\n\n\n";
	cout << "\n\n\t\t 6-желтый, 7-белый, 8-серый, 9-светло/синий,  a-светло/зеленый, b-светло/голубой\n\n";
	cout << "\n\n\t\t c-светло/красный, d-светло/лиловый, e-светло/желтый, f-ярко/белый\n\n";
	
	char cv_kon, cv_shr;	 //cv_kon -цвет консоли, cv_shr - цвет шрифта
	int schet = 0, schet2 = 0;		  //	счетчики ошибок: 1 неправильный ввод, 2 одинаковые цвета
	cout << "\n\t\tВведи цвет консоли \t";
	cin >> cv_kon;	   
	cout << "\n";
	cout << "\n\t\tВведи цвет шрифта \t";
	cin >> cv_shr;
	cout << "\n";
	//cout << "\t\tcv_kon = \t" << cv_kon<< "\n";
	//cout << "\t\tcv_shr = \t" << cv_shr << "\n";
	if (((cv_kon == '0') && (cv_shr == '0')) || ((cv_kon == '1') && (cv_shr == '1')) || ((cv_kon == '2') && (cv_shr == '2')) || ((cv_kon == '3') && (cv_shr == '3')) || ((cv_kon == '4') && (cv_shr == '4')) || ((cv_kon == '5') && (cv_shr == '5')) || ((cv_kon == '6') && (cv_shr == '6')) || ((cv_kon == '7') && (cv_shr == '7')) || ((cv_kon == '8') && (cv_shr == '8')) || ((cv_kon == '9') && (cv_shr == '9')) || ((cv_kon == 'a') && (cv_shr == 'a')) || ((cv_kon == 'b') && (cv_shr == 'b')) || ((cv_kon == 'c') && (cv_shr == 'c')) || ((cv_kon == 'd') && (cv_shr == 'd')) || ((cv_kon == 'e') && (cv_shr == 'e')) || ((cv_kon == 'f') && (cv_shr == 'f'))) //проверка одинакового ввода цветов
	{
		cout << "\n\n\t\t\tО д и н а к о в ы е   ц в е т а ! ! !\n\n\t\t\t      П О В Т О Р И   В В О Д \n";
		schet2++;			  //	счетчик ошибки ввода одинакового цвета
		//cout << schet2;
	}	
	
	else
	{
		((cv_kon == '0') && (cv_shr == '1')) ? system("color 01") : ((cv_kon == '0') && (cv_shr == '2')) ? system("color 02") : ((cv_kon == '0') && (cv_shr == '3')) ? system("color 03") : ((cv_kon == '0') && (cv_shr == '4')) ? system("color 04") : ((cv_kon == '0') && (cv_shr == '5')) ? system("color 05") : ((cv_kon == '0') && (cv_shr == '6')) ? system("color 06") : ((cv_kon == '0') && (cv_shr == '7')) ? system("color 07") : ((cv_kon == '0') && (cv_shr == '8')) ? system("color 08") : ((cv_kon == '0') && (cv_shr == '9')) ? system("color 09") : ((cv_kon == '0') && (cv_shr == 'a')) ? system("color 0a") : ((cv_kon == '0') && (cv_shr == 'b')) ? system("color 0b") : ((cv_kon == '0') && (cv_shr == 'c')) ? system("color 0c") : ((cv_kon == '0') && (cv_shr == 'd')) ? system("color 0d") : ((cv_kon == '0') && (cv_shr == 'e')) ? system("color 0e") : ((cv_kon == '0') && (cv_shr == 'f')) ? system("color 0f") : schet++; // алгоритм выбора цветов, через тенарный оператор. Плюс счетчик ошибок
		((cv_kon == '1') && (cv_shr == '0')) ? system("color 10") : ((cv_kon == '1') && (cv_shr == '2')) ? system("color 12") : ((cv_kon == '1') && (cv_shr == '3')) ? system("color 13") : ((cv_kon == '1') && (cv_shr == '4')) ? system("color 14") : ((cv_kon == '1') && (cv_shr == '5')) ? system("color 15") : ((cv_kon == '1') && (cv_shr == '6')) ? system("color 16") : ((cv_kon == '1') && (cv_shr == '7')) ? system("color 17") : ((cv_kon == '1') && (cv_shr == '8')) ? system("color 18") : ((cv_kon == '1') && (cv_shr == '9')) ? system("color 19") : ((cv_kon == '1') && (cv_shr == 'a')) ? system("color 1a") : ((cv_kon == '1') && (cv_shr == 'b')) ? system("color 1b") : ((cv_kon == '1') && (cv_shr == 'c')) ? system("color 1c") : ((cv_kon == '1') && (cv_shr == 'd')) ? system("color 1d") : ((cv_kon == '1') && (cv_shr == 'e')) ? system("color 1e") : ((cv_kon == '1') && (cv_shr == 'f')) ? system("color 1f") : schet++;
		((cv_kon == '2') && (cv_shr == '0')) ? system("color 20") : ((cv_kon == '2') && (cv_shr == '1')) ? system("color 21") : ((cv_kon == '2') && (cv_shr == '3')) ? system("color 23") : ((cv_kon == '2') && (cv_shr == '4')) ? system("color 24") : ((cv_kon == '2') && (cv_shr == '5')) ? system("color 25") : ((cv_kon == '2') && (cv_shr == '6')) ? system("color 26") : ((cv_kon == '2') && (cv_shr == '7')) ? system("color 27") : ((cv_kon == '2') && (cv_shr == '8')) ? system("color 28") : ((cv_kon == '2') && (cv_shr == '9')) ? system("color 29") : ((cv_kon == '2') && (cv_shr == 'a')) ? system("color 2a") : ((cv_kon == '2') && (cv_shr == 'b')) ? system("color 2b") : ((cv_kon == '2') && (cv_shr == 'c')) ? system("color 2c") : ((cv_kon == '2') && (cv_shr == 'd')) ? system("color 2d") : ((cv_kon == '2') && (cv_shr == 'e')) ? system("color 2e") : ((cv_kon == '2') && (cv_shr == 'f')) ? system("color 2f") : schet++;
		((cv_kon == '3') && (cv_shr == '0')) ? system("color 30") : ((cv_kon == '3') && (cv_shr == '1')) ? system("color 31") : ((cv_kon == '3') && (cv_shr == '2')) ? system("color 32") : ((cv_kon == '3') && (cv_shr == '4')) ? system("color 34") : ((cv_kon == '3') && (cv_shr == '5')) ? system("color 35") : ((cv_kon == '3') && (cv_shr == '6')) ? system("color 36") : ((cv_kon == '3') && (cv_shr == '7')) ? system("color 37") : ((cv_kon == '3') && (cv_shr == '8')) ? system("color 38") : ((cv_kon == '3') && (cv_shr == '9')) ? system("color 39") : ((cv_kon == '3') && (cv_shr == 'a')) ? system("color 3a") : ((cv_kon == '3') && (cv_shr == 'b')) ? system("color 3b") : ((cv_kon == '3') && (cv_shr == 'c')) ? system("color 3c") : ((cv_kon == '3') && (cv_shr == 'd')) ? system("color 3d") : ((cv_kon == '3') && (cv_shr == 'e')) ? system("color 3e") : ((cv_kon == '3') && (cv_shr == 'f')) ? system("color 3f") : schet++;
		((cv_kon == '4') && (cv_shr == '0')) ? system("color 40") : ((cv_kon == '4') && (cv_shr == '1')) ? system("color 41") : ((cv_kon == '4') && (cv_shr == '2')) ? system("color 42") : ((cv_kon == '4') && (cv_shr == '3')) ? system("color 43") : ((cv_kon == '4') && (cv_shr == '5')) ? system("color 45") : ((cv_kon == '4') && (cv_shr == '6')) ? system("color 46") : ((cv_kon == '4') && (cv_shr == '7')) ? system("color 47") : ((cv_kon == '4') && (cv_shr == '8')) ? system("color 48") : ((cv_kon == '4') && (cv_shr == '9')) ? system("color 49") : ((cv_kon == '4') && (cv_shr == 'a')) ? system("color 4a") : ((cv_kon == '4') && (cv_shr == 'b')) ? system("color 4b") : ((cv_kon == '4') && (cv_shr == 'c')) ? system("color 4c") : ((cv_kon == '4') && (cv_shr == 'd')) ? system("color 4d") : ((cv_kon == '4') && (cv_shr == 'e')) ? system("color 4e") : ((cv_kon == '4') && (cv_shr == 'f')) ? system("color 4f") : schet++;
		((cv_kon == '5') && (cv_shr == '0')) ? system("color 50") : ((cv_kon == '5') && (cv_shr == '1')) ? system("color 51") : ((cv_kon == '5') && (cv_shr == '2')) ? system("color 52") : ((cv_kon == '5') && (cv_shr == '3')) ? system("color 53") : ((cv_kon == '5') && (cv_shr == '4')) ? system("color 54") : ((cv_kon == '5') && (cv_shr == '6')) ? system("color 56") : ((cv_kon == '5') && (cv_shr == '7')) ? system("color 57") : ((cv_kon == '5') && (cv_shr == '8')) ? system("color 58") : ((cv_kon == '5') && (cv_shr == '9')) ? system("color 59") : ((cv_kon == '5') && (cv_shr == 'a')) ? system("color 5a") : ((cv_kon == '5') && (cv_shr == 'b')) ? system("color 5b") : ((cv_kon == '5') && (cv_shr == 'c')) ? system("color 5c") : ((cv_kon == '5') && (cv_shr == 'd')) ? system("color 5d") : ((cv_kon == '5') && (cv_shr == 'e')) ? system("color 5e") : ((cv_kon == '5') && (cv_shr == 'f')) ? system("color 5f") : schet++;
		((cv_kon == '6') && (cv_shr == '0')) ? system("color 60") : ((cv_kon == '6') && (cv_shr == '1')) ? system("color 61") : ((cv_kon == '6') && (cv_shr == '2')) ? system("color 62") : ((cv_kon == '6') && (cv_shr == '3')) ? system("color 63") : ((cv_kon == '6') && (cv_shr == '4')) ? system("color 64") : ((cv_kon == '6') && (cv_shr == '5')) ? system("color 65") : ((cv_kon == '6') && (cv_shr == '7')) ? system("color 67") : ((cv_kon == '6') && (cv_shr == '8')) ? system("color 68") : ((cv_kon == '6') && (cv_shr == '9')) ? system("color 69") : ((cv_kon == '6') && (cv_shr == 'a')) ? system("color 6a") : ((cv_kon == '6') && (cv_shr == 'b')) ? system("color 6b") : ((cv_kon == '6') && (cv_shr == 'c')) ? system("color 6c") : ((cv_kon == '6') && (cv_shr == 'd')) ? system("color 6d") : ((cv_kon == '6') && (cv_shr == 'e')) ? system("color 6e") : ((cv_kon == '6') && (cv_shr == 'f')) ? system("color 6f") : schet++;
		((cv_kon == '7') && (cv_shr == '0')) ? system("color 70") : ((cv_kon == '7') && (cv_shr == '1')) ? system("color 71") : ((cv_kon == '7') && (cv_shr == '2')) ? system("color 72") : ((cv_kon == '7') && (cv_shr == '3')) ? system("color 73") : ((cv_kon == '7') && (cv_shr == '4')) ? system("color 74") : ((cv_kon == '7') && (cv_shr == '5')) ? system("color 75") : ((cv_kon == '7') && (cv_shr == '6')) ? system("color 76") : ((cv_kon == '7') && (cv_shr == '8')) ? system("color 78") : ((cv_kon == '7') && (cv_shr == '9')) ? system("color 79") : ((cv_kon == '7') && (cv_shr == 'a')) ? system("color 7a") : ((cv_kon == '7') && (cv_shr == 'b')) ? system("color 7b") : ((cv_kon == '7') && (cv_shr == 'c')) ? system("color 7c") : ((cv_kon == '7') && (cv_shr == 'd')) ? system("color 7d") : ((cv_kon == '7') && (cv_shr == 'e')) ? system("color 7e") : ((cv_kon == '7') && (cv_shr == 'f')) ? system("color 7f") : schet++;
		((cv_kon == '8') && (cv_shr == '0')) ? system("color 80") : ((cv_kon == '8') && (cv_shr == '1')) ? system("color 81") : ((cv_kon == '8') && (cv_shr == '2')) ? system("color 82") : ((cv_kon == '8') && (cv_shr == '3')) ? system("color 83") : ((cv_kon == '8') && (cv_shr == '4')) ? system("color 84") : ((cv_kon == '8') && (cv_shr == '5')) ? system("color 85") : ((cv_kon == '8') && (cv_shr == '6')) ? system("color 86") : ((cv_kon == '8') && (cv_shr == '7')) ? system("color 87") : ((cv_kon == '8') && (cv_shr == '9')) ? system("color 89") : ((cv_kon == '8') && (cv_shr == 'a')) ? system("color 8a") : ((cv_kon == '8') && (cv_shr == 'b')) ? system("color 8b") : ((cv_kon == '8') && (cv_shr == 'c')) ? system("color 8c") : ((cv_kon == '8') && (cv_shr == 'd')) ? system("color 8d") : ((cv_kon == '8') && (cv_shr == 'e')) ? system("color 8e") : ((cv_kon == '8') && (cv_shr == 'f')) ? system("color 8f") : schet++;
		((cv_kon == '9') && (cv_shr == '0')) ? system("color 90") : ((cv_kon == '9') && (cv_shr == '1')) ? system("color 91") : ((cv_kon == '9') && (cv_shr == '2')) ? system("color 92") : ((cv_kon == '9') && (cv_shr == '3')) ? system("color 93") : ((cv_kon == '9') && (cv_shr == '4')) ? system("color 94") : ((cv_kon == '9') && (cv_shr == '5')) ? system("color 95") : ((cv_kon == '9') && (cv_shr == '6')) ? system("color 96") : ((cv_kon == '9') && (cv_shr == '7')) ? system("color 97") : ((cv_kon == '9') && (cv_shr == '8')) ? system("color 98") : ((cv_kon == '9') && (cv_shr == 'a')) ? system("color 9a") : ((cv_kon == '9') && (cv_shr == 'b')) ? system("color 9b") : ((cv_kon == '9') && (cv_shr == 'c')) ? system("color 9c") : ((cv_kon == '9') && (cv_shr == 'd')) ? system("color 9d") : ((cv_kon == '9') && (cv_shr == 'e')) ? system("color 9e") : ((cv_kon == '9') && (cv_shr == 'f')) ? system("color 9f") : schet++;
		((cv_kon == 'a') && (cv_shr == '0')) ? system("color a0") : ((cv_kon == 'a') && (cv_shr == '1')) ? system("color a1") : ((cv_kon == 'a') && (cv_shr == '2')) ? system("color a2") : ((cv_kon == 'a') && (cv_shr == '3')) ? system("color a3") : ((cv_kon == 'a') && (cv_shr == '4')) ? system("color a4") : ((cv_kon == 'a') && (cv_shr == '5')) ? system("color a5") : ((cv_kon == 'a') && (cv_shr == '6')) ? system("color a6") : ((cv_kon == 'a') && (cv_shr == '7')) ? system("color a7") : ((cv_kon == 'a') && (cv_shr == '8')) ? system("color a8") : ((cv_kon == 'a') && (cv_shr == '9')) ? system("color a9") : ((cv_kon == 'a') && (cv_shr == 'b')) ? system("color ab") : ((cv_kon == 'a') && (cv_shr == 'c')) ? system("color ac") : ((cv_kon == 'a') && (cv_shr == 'd')) ? system("color ad") : ((cv_kon == 'a') && (cv_shr == 'e')) ? system("color ae") : ((cv_kon == 'a') && (cv_shr == 'f')) ? system("color af") : schet++;
		((cv_kon == 'b') && (cv_shr == '0')) ? system("color b0") : ((cv_kon == 'b') && (cv_shr == '1')) ? system("color b1") : ((cv_kon == 'b') && (cv_shr == '2')) ? system("color b2") : ((cv_kon == 'b') && (cv_shr == '3')) ? system("color b3") : ((cv_kon == 'b') && (cv_shr == '4')) ? system("color b4") : ((cv_kon == 'b') && (cv_shr == '5')) ? system("color b5") : ((cv_kon == 'b') && (cv_shr == '6')) ? system("color b6") : ((cv_kon == 'b') && (cv_shr == '7')) ? system("color b7") : ((cv_kon == 'b') && (cv_shr == '8')) ? system("color b8") : ((cv_kon == 'b') && (cv_shr == '9')) ? system("color b9") : ((cv_kon == 'b') && (cv_shr == 'a')) ? system("color ba") : ((cv_kon == 'b') && (cv_shr == 'c')) ? system("color bc") : ((cv_kon == 'b') && (cv_shr == 'd')) ? system("color bd") : ((cv_kon == 'b') && (cv_shr == 'e')) ? system("color be") : ((cv_kon == 'b') && (cv_shr == 'f')) ? system("color bf") : schet++;
		((cv_kon == 'c') && (cv_shr == '0')) ? system("color c0") : ((cv_kon == 'c') && (cv_shr == '1')) ? system("color c1") : ((cv_kon == 'c') && (cv_shr == '2')) ? system("color c2") : ((cv_kon == 'c') && (cv_shr == '3')) ? system("color c3") : ((cv_kon == 'c') && (cv_shr == '4')) ? system("color c4") : ((cv_kon == 'c') && (cv_shr == '5')) ? system("color c5") : ((cv_kon == 'c') && (cv_shr == '6')) ? system("color c6") : ((cv_kon == 'c') && (cv_shr == '7')) ? system("color c7") : ((cv_kon == 'c') && (cv_shr == '8')) ? system("color c8") : ((cv_kon == 'c') && (cv_shr == '9')) ? system("color c9") : ((cv_kon == 'c') && (cv_shr == 'a')) ? system("color ca") : ((cv_kon == 'c') && (cv_shr == 'b')) ? system("color cb") : ((cv_kon == 'c') && (cv_shr == 'd')) ? system("color cd") : ((cv_kon == 'c') && (cv_shr == 'e')) ? system("color ce") : ((cv_kon == 'c') && (cv_shr == 'f')) ? system("color cf") : schet++;
		((cv_kon == 'd') && (cv_shr == '0')) ? system("color d0") : ((cv_kon == 'd') && (cv_shr == '1')) ? system("color d1") : ((cv_kon == 'd') && (cv_shr == '2')) ? system("color d2") : ((cv_kon == 'd') && (cv_shr == '3')) ? system("color d3") : ((cv_kon == 'd') && (cv_shr == '4')) ? system("color d4") : ((cv_kon == 'd') && (cv_shr == '5')) ? system("color d5") : ((cv_kon == 'd') && (cv_shr == '6')) ? system("color d6") : ((cv_kon == 'd') && (cv_shr == '7')) ? system("color d7") : ((cv_kon == 'd') && (cv_shr == '8')) ? system("color d8") : ((cv_kon == 'd') && (cv_shr == '9')) ? system("color d9") : ((cv_kon == 'd') && (cv_shr == 'a')) ? system("color da") : ((cv_kon == 'd') && (cv_shr == 'b')) ? system("color db") : ((cv_kon == 'd') && (cv_shr == 'c')) ? system("color dc") : ((cv_kon == 'd') && (cv_shr == 'e')) ? system("color de") : ((cv_kon == 'd') && (cv_shr == 'f')) ? system("color df") : schet++;
		((cv_kon == 'e') && (cv_shr == '0')) ? system("color e0") : ((cv_kon == 'e') && (cv_shr == '1')) ? system("color e1") : ((cv_kon == 'e') && (cv_shr == '2')) ? system("color e2") : ((cv_kon == 'e') && (cv_shr == '3')) ? system("color e3") : ((cv_kon == 'e') && (cv_shr == '4')) ? system("color e4") : ((cv_kon == 'e') && (cv_shr == '5')) ? system("color e5") : ((cv_kon == 'e') && (cv_shr == '6')) ? system("color e6") : ((cv_kon == 'e') && (cv_shr == '7')) ? system("color e7") : ((cv_kon == 'e') && (cv_shr == '8')) ? system("color e8") : ((cv_kon == 'e') && (cv_shr == '9')) ? system("color e9") : ((cv_kon == 'e') && (cv_shr == 'a')) ? system("color ea") : ((cv_kon == 'e') && (cv_shr == 'b')) ? system("color eb") : ((cv_kon == 'e') && (cv_shr == 'c')) ? system("color ec") : ((cv_kon == 'e') && (cv_shr == 'd')) ? system("color ed") : ((cv_kon == 'e') && (cv_shr == 'f')) ? system("color ef") : schet++;
		((cv_kon == 'f') && (cv_shr == '0')) ? system("color f0") : ((cv_kon == 'f') && (cv_shr == '1')) ? system("color f1") : ((cv_kon == 'f') && (cv_shr == '2')) ? system("color f2") : ((cv_kon == 'f') && (cv_shr == '3')) ? system("color f3") : ((cv_kon == 'f') && (cv_shr == '4')) ? system("color f4") : ((cv_kon == 'f') && (cv_shr == '5')) ? system("color f5") : ((cv_kon == 'f') && (cv_shr == '6')) ? system("color f6") : ((cv_kon == 'f') && (cv_shr == '7')) ? system("color f7") : ((cv_kon == 'f') && (cv_shr == '8')) ? system("color f8") : ((cv_kon == 'f') && (cv_shr == '9')) ? system("color f9") : ((cv_kon == 'f') && (cv_shr == 'a')) ? system("color fa") : ((cv_kon == 'f') && (cv_shr == 'b')) ? system("color fb") : ((cv_kon == 'f') && (cv_shr == 'c')) ? system("color fc") : ((cv_kon == 'f') && (cv_shr == 'd')) ? system("color fd") : ((cv_kon == 'f') && (cv_shr == 'e')) ? system("color fe") : schet++;

	}
	if (schet >= 16) 						  //  проверка счетчика неправильного ввода, если он больше  или равен количеству строк алгоритма выбора цветов, выводится сообщение об ошибке.
	{
		cout << "\n\n\t\tН Е В Е Р Н Ы Е   З Н А Ч Е Н И Я   Ц В Е Т О В\n\n\t\t\t   П О В Т О Р И   В В О Д\n\n";
		cout << schet;

	}
	if ((schet < 16) && (schet2 < 1))			//проверка счетчиков ошибок. Если все ОК, выводится сообщение
	{
		cout<<"\n\n\t\t\t\tП Р О В Е Р К А   Ц В Е Т О В\n\n\n";
	}
}
